//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
<<<<<<< Updated upstream
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplicationAssigment.pages.profile
{
    public partial class LoginScreen
    {
=======
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationAssigment.pages.profile
{


    public partial class LoginScreen
    {

        /// <summary>
        /// LoginNav control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebApplicationAssigment.pages.widget.LoginNav LoginNav;
>>>>>>> Stashed changes
    }
}
