//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationAssigment.pages.profile
{


    public partial class ProfileScreen
    {

        /// <summary>
<<<<<<< Updated upstream
        /// Profile control.
=======
        /// profilemou control.
>>>>>>> Stashed changes
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
<<<<<<< Updated upstream
        protected global::WebApplicationAssigment.pages.widget.Profile Profile;
=======
        protected global::WebApplicationAssigment.pages.widget.profilemou profilemou;
>>>>>>> Stashed changes
    }
}
