<%@ Page Title="" Language="C#" MasterPageFile="~/pages/master/Master.Master" AutoEventWireup="true" CodeBehind="UserRoles2.aspx.cs" Inherits="WebApplicationAssigment.pages.main.admin.UserRoles2.aspx" %>

<%@ Import Namespace="WebApplicationAssigment.modal" %>


<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">




    <div class="container">

        <div class="row">
            <div class="col-md-12 d-flex justify-content-center">
                <asp:Label ID="Label1" runat="server" Text="USer roles" CssClass="text-lg-center"></asp:Label>
            </div>
            <center>
            <div id="preview" class="float-center" runat="server"></div>
                </center>
            <br>
            <div class="col-md-12 d-flex justify-content-center">

                <asp:GridView
                    ID="GridView1"
                    runat="server"
                    class="table table-borderless table-condensed table-responsive table-hover "
                    AutoGenerateColumns="False"
                    AutoGenerateDeleteButton="False"
                    DataSourceID="SqlDataSource1"
                    ShowHeaderWhenEmpty="True">
                    <Columns>

                        <asp:TemplateField HeaderText="Art Image" SortExpression="image">
                            <ItemTemplate>
                                <asp:Label ID="Label2" runat="server" Text="<%# Eval("UserId") %>"></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        
                        <asp:TemplateField HeaderText="Art Image" SortExpression="image">
                            <ItemTemplate>
                                <asp:Image ID="Image1" runat="server" ImageUrl='<%# Eval("UserId", "~/commons/UserProfilePicture.ashx?guid={0}")%>' Height="50" Width="50" />
                            </ItemTemplate>
                        </asp:TemplateField>

                        <asp:TemplateField HeaderText="Art Image">
                            <ItemTemplate>
                                <asp:CheckBox ID="ckbRoleAdmin" runat="server" />
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Author">
                            <ItemTemplate>
                                <asp:CheckBox ID="ckbRoleAuthor" runat="server" />
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Art Image">
                            <ItemTemplate>
                                <asp:CheckBox ID="ckbRoleEditor" runat="server" />
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Art Image">
                            <ItemTemplate>
                                <asp:CheckBox ID="ckbRoleArtist" runat="server" />
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Art Image">
                            <ItemTemplate>
                                <asp:CheckBox ID="ckbRoleCustomer" runat="server" />
                            </ItemTemplate>
                        </asp:TemplateField>



                        <asp:TemplateField HeaderText="Remove" ShowHeader="False">
                            <ItemTemplate>
                                <asp:LinkButton
                                    ID="btnRemoveItem"
                                    runat="server"
                                    CausesValidation="false"
                                    Text="&#x1F5D1;"
                                    ControlStyle-CssClass="text-danger"
                                    CommandArgument='<%# Eval("art_id") %>'
                                    OnCommand="btnDeleteEvent" />
                            </ItemTemplate>
                        </asp:TemplateField>
                    </Columns>
                </asp:GridView>
                <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\ArtShop.mdf;Integrated Security=True;MultipleActiveResultSets=True;Connect Timeout=30;Application Name=EntityFramework" ProviderName="System.Data.SqlClient"
                    SelectCommand="SELECT * FROM [vw_customer_cart] WHERE user_id = @user_id"
                    DeleteCommand="DELETE FROM [CartDetails] WHERE [cart_id] = @cart_id AND [art_id] = @art_id">
                    <SelectParameters>
                        <asp:Parameter Name="user_id" Type="String" />
                    </SelectParameters>
                    <DeleteParameters>
                        <asp:Parameter Name="cart_id" Type="Int32" />
                        <asp:Parameter Name="art_id" Type="Int32" />
                    </DeleteParameters>

                </asp:SqlDataSource>


            </div>
            <div class="col-md-12 text-right">
                <asp:Label ID="totalprice" runat="server" Text="TOTAL:"></asp:Label>
            </div>

            <div class="col-md-12 text-right">
                <asp:Button ID="Button2" CssClass="btn btn-danger" runat="server" Text="Check Out to payment" />
            </div>

        </div>
    </div>





</asp:Content>
