//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationAssigment.modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartDetail
    {
        public int cart_id { get; set; }
        public int art_id { get; set; }
        public Nullable<int> availability { get; set; }
        public Nullable<System.DateTime> add_date { get; set; }
    
        public virtual Art Art { get; set; }
        public virtual Cart Cart { get; set; }
    }
}
