//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationAssigment.modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Delivery()
        {
            this.PaymentDetails = new HashSet<PaymentDetail>();
            this.DeliveryChains = new HashSet<DeliveryChain>();
        }
    
        public System.Guid id { get; set; }
        public System.Guid source { get; set; }
        public System.Guid destination { get; set; }
        public string delivery_note { get; set; }
        public System.Guid final_delivery_status { get; set; }
        public System.Guid delivery_company { get; set; }
        public Nullable<System.DateTime> recive_dates { get; set; }
        public byte[] recive_prove { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Address Address1 { get; set; }
        public virtual DeliveryCompany DeliveryCompany { get; set; }
        public virtual DeliveryStatu DeliveryStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentDetail> PaymentDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryChain> DeliveryChains { get; set; }
    }
}
