//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationAssigment.modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryChain
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeliveryChain()
        {
            this.Deliveries = new HashSet<Delivery>();
        }
    
        public System.Guid id { get; set; }
        public System.DateTime arrival_dates { get; set; }
        public System.Guid address_id { get; set; }
        public Nullable<System.Guid> delivery_status { get; set; }
        public string notes { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual DeliveryStatu DeliveryStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Delivery> Deliveries { get; set; }
    }
}
