//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationAssigment.modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Painting
    {
        public int art_id { get; set; }
        public int quantity { get; set; }
        public int weight_g { get; set; }
        public int height_mm { get; set; }
        public int width_mm { get; set; }
        public int lenght_mm { get; set; }
    
        public virtual Art Art { get; set; }
    }
}
