//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationAssigment.modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> payment_method_id { get; set; }
        public Nullable<double> tax_change { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public string payment_status { get; set; }
    }
}
