//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationAssigment.modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublicBank
    {
        public string bank_account { get; set; }
        public string name { get; set; }
        public string bank_username { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string password { get; set; }
    }
}
