//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationAssigment.modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public System.Guid UserId { get; set; }
        public int priority { get; set; }
        public int position_id { get; set; }
        public byte[] picture { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual Position Position { get; set; }
    }
}
