//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationAssigment.modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAddress
    {
        public System.Guid UserId { get; set; }
        public System.Guid address_id { get; set; }
        public string name { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual UserExtension UserExtension { get; set; }
    }
}
