//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationAssigment.modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class vW_users_address
    {
        public System.Guid id { get; set; }
        public double latitude { get; set; }
        public double longitude { get; set; }
        public string details { get; set; }
        public string street { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string poscode { get; set; }
        public string country { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid address_id { get; set; }
        public string name { get; set; }
    }
}
